gui_title = ":books: FOIArchive"
tab_title = "HL: FOIArchive"
favicon = "static/hl-logo-favicon.png"
search_str_help="""
Use double quotes for phrases, OR for logical or, and - for logical not.
"""
corpus_placeholder="""
Optionally restrict to specific corpora
"""
classification_placeholder="""
Optionally restrict to specific classifications
"""
classification_help="""
Some documents do not include original classification in metadata, so consider
including the 'unknown' classification when searching by classification.
"""
date_help="""
Some documents do not include date metadata, so we default to including 
documents without a date.
"""
help_action = "mailto:info@history-lab.org?subject=History Lab Help Request"
bug_action= "mailto:info@history-lab.org?subject=History Lab Bug Report"
about_body = """
Built by Columbia University's [History Lab](http://history-lab.org) with generous support 
from the NEH.
"""
corpora_description="static/corpora_description.md"
#
table_name = "foiarchive.docs"
max_rows = 2000     # results must be <= to display detail records
# not used currently but should be
# schema =
# tsvector_col =