gui_title = ":books: FOIArchive"
favicon = "static/hl-logo-favicon.png"
search_str_help="""
Use double quotes for phrases, OR for logical or, and - for logical not.
"""
corpus_placeholder="""
Optionally restrict to specific corpora
"""
classification_placeholder="""
Optionally restrict to specific classifications
"""
classification_help="""
Some documents do not include original classification in metadata, so consider
including the 'unknown' classification when searching by classification.
"""
entity_placeholder="""
Optionally restrict to specific entities
"""
entity_help="""
Select documents referencing specific people, organizatons, locations, 
government and other concepts identifed by named entity recogntion (NER).
If selecting multiple entities, and you wish to only view documents that 
contain all entities, please check 'All Entities Appear in Document'.
NOTE: entities are only available for the UN and FRUS corpora.
"""
date_help="""
Some documents do not include date metadata. You can expand your search
to include these documents by checking 'Include 
documents without a date'.
"""
help_action = "mailto:info@history-lab.org?subject=History Lab Help Request"
bug_action= "mailto:info@history-lab.org?subject=History Lab Bug Report"
about_body = """
Built by Columbia University's [History Lab](http://history-lab.org) with generous support 
from the NEH.
"""
corpora_description="static/corpora_description.md"
#
table_name = "foiarchive.docs"
max_rows = 2000     # results must be <= to display detail records
#
docviewer_url="https://foiarchive-docviewer.streamlit.app"
#
sidebar_footer="""
Need assistance or have feedback to share? Don't hesitate to 
[contact us](mailto:info@history-lab.org?subject=FOIArchive%20Search).
"""
# not used currently but should be
# schema =
# tsvector_col =